// `@wasm/bclibc` is generated by `make build-wasm` (scripts/embed-wasm.mjs): the bare WebAssembly module of bclibc, as
// base64. This stub is what the type checker sees when it has not been built yet.
declare const wasmBase64: string;
export default wasmBase64;
