#!/usr/bin/env node
// Embeds a WebAssembly module in a JavaScript module as base64, so the library is one file that needs no asset
// handling from a bundler: `node scripts/embed-wasm.mjs <in.wasm> <out.js>`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname } from "node:path";

const [input, output] = process.argv.slice(2);
if (!input || !output) {
    console.error("usage: embed-wasm.mjs <in.wasm> <out.js>");
    process.exit(2);
}
const base64 = readFileSync(input).toString("base64");
mkdirSync(dirname(output), { recursive: true });
writeFileSync(
    output,
    `// Generated by scripts/embed-wasm.mjs from ${basename(input)}: bclibc's bare WebAssembly module, as base64.\nexport default "${base64}";\n`
);
console.log(`${output}: ${readFileSync(input).length} bytes of wasm, ${base64.length} of base64`);
